language: generic
env:
  global:
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="mrchecker"
    - REPO_DEST="mrchecker.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: CYp9HYG5uMzo75LkKX5RSO3H39jTBN216YLj7oeZGA53aQbL1TXYRYdY49UC8ZmuUkJN+meIuaA3UIl8CwvW3Un/HDLgol7hI/qOcMv7Zouu56ycCGBCvFfqEiSRgbDx9EoHYzNAXpUM1ww5NMkmlmk1ndYtzDi5im8M2P04QJvS7lppdFUItisfstFddJYLl97ARwGAM7X2cvFTejDUY+YRBf8aMy2VNizvbsFsDIcPD/E4u2rg5uBHiAglB+I80iEDMKXYpu0CgNZiLHghu3Q7aI2R1fFxlaKOMbyWHCT/b79BwcqUHASu7+SWdb6G5B6jjoymsSibCjqcUEW4LV1LyNp6fBsDLh0Ze1xUktvCTO+NZzCIXjKrSxhFMa6R5QkjqViKC17FA73o9Wfp/Yfl021YOzz7MRegAmDRalY4VH7aP/zNiTk9BcJdOnUlsuaoZtHmw7bqk1pEg9b3xw4ZnTpXrRTM6Xao8wNy5T2Bsdtx0zrWjU2iE+Y39K7nOu+oeUUJx0g1dpAzLWVV+gEgnDAS3e0suZzOk41zci6BCACDIBXmSVYWUZDWWdBoVPuCbZjYGb248gysvM9qp8RfI8WGdPu1I4VlJJ1Q+k4a/nOVrMHebwtnHEiBdrVCNaFQK1cfg+yfZkn/7JuVQaSY5to9sH7DIgvkt9ZERkk=
stages:
  - name: Documentation
    if: (branch = develop) AND (type = push)
jobs:
  include:
    - stage: Documentation
      script:
        # Clone repositories
        - git clone -b develop --single-branch https://${GH_REPO_SOURCE}
        - git clone https://${GH_REPO_DEST}
        - git clone https://${GH_REPO_CONSOLIDATE}
        # Update wiki repository with documentation folder contents
        - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
        - cd ${REPO_DEST}
        - grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
        # Terminate Travis CI build when no changes detected
        - |
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            git config user.email ${EMAIL}
            git config user.name ${USER}
            git status
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_DEST}"
            git push origin-wiki master
            cd ../${REPO_CONSOLIDATE}
            if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
            git submodule init
            git submodule update --recursive --remote
            cd ${REPO_DEST}
            git checkout master
            git pull
            cd ..
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${USER}:${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
            git push origin-wiki master
          fi
